(function(){
  const order=['phishing','simswap','whatsapp','qrcode','support','marketplace','job','boleto'];
  const TOTAL=order.length;
  const titles={
    phishing:'Phishing ou mensagem legítima?',simswap:'SIM Swap ou falha comum?',whatsapp:'Perfil falso ou contato legítimo?',
    qrcode:'QR Code legítimo ou adulterado?',support:'Alerta real ou falso suporte técnico?',marketplace:'Venda legítima ou golpe no marketplace?',
    job:'Oportunidade real ou vaga falsa?',boleto:'Cobrança legítima ou boleto adulterado?'
  };
  const names={phishing:'Análise de e-mail',simswap:'Análise da linha móvel',whatsapp:'Análise da conversa',qrcode:'Análise do QR Code',support:'Análise do suporte técnico',marketplace:'Análise do marketplace',job:'Análise da vaga',boleto:'Análise da cobrança'};
  const shortLabels={phishing:'E-mail',simswap:'Linha móvel',whatsapp:'Conversa',qrcode:'QR Code',support:'Suporte técnico',marketplace:'Marketplace',job:'Vaga de emprego',boleto:'Cobrança'};
  const I=(name,size=18)=>window.AntiScamIcons.icon(name,size); let currentChallenge=null;
  const modules={phishing:()=>window.PhishingSimulation,simswap:()=>window.SimSwapSimulation,whatsapp:()=>window.WhatsAppSimulation,qrcode:()=>window.QRCodeSimulation,support:()=>window.SupportSimulation,marketplace:()=>window.MarketplaceSimulation,job:()=>window.JobSimulation,boleto:()=>window.BoletoSimulation};
  const achievements={
    'olho-clinico':{icon:'eye',title:'Olho Clínico',text:'Encontrou evidências em diferentes partes das simulações.'},
    'analista-links':{icon:'link',title:'Analista de Links',text:'Inspecionou o destino de um link antes de confiar.'},
    'sem-pressa':{icon:'clock',title:'Sem Pressa',text:'Investigou vários sinais antes de encerrar a análise.'},
    'investigador-de-sinais':{icon:'network',title:'Investigador de Sinais',text:'Relacionou perda de sinal com outras evidências.'},
    'leitor-de-contexto':{icon:'message',title:'Leitor de Contexto',text:'Analisou vários elementos da conversa antes de decidir.'}
  };
  const preventionItems=[
    {icon:'clock',title:'Desconfie da urgência',short:'Pressão reduz seu tempo de análise.',text:'Golpistas tentam criar pressa com bloqueios, vencimentos ou pedidos “para agora”. Pare e procure evidências antes de agir.'},
    {icon:'mail',title:'Verifique o remetente',short:'Leia o endereço completo.',text:'O nome exibido pode ser imitado. Compare o domínio completo e procure pequenas trocas de caracteres ou endereços extras.'},
    {icon:'link',title:'Não confie em links inesperados',short:'Prefira acessar o serviço por conta própria.',text:'Abra o aplicativo oficial ou digite um endereço que você já conhece em vez de depender do link da mensagem.'},
    {icon:'qr-code',title:'Confira QR Codes antes de pagar',short:'Veja destino e beneficiário.',text:'QR Codes podem ser substituídos por adesivos ou levar a destinos diferentes. Confira beneficiário, valor e, quando possível, valide no canal oficial.'},
    {icon:'key',title:'Não compartilhe códigos',short:'Códigos de autenticação são pessoais.',text:'Códigos de verificação e recuperação podem dar acesso a contas. Não envie códigos por conversa para “confirmar” sua identidade.'},
    {icon:'phone',title:'Confirme por outro canal',short:'Especialmente quando envolve dinheiro.',text:'Se alguém aparecer com número novo, suporte inesperado ou pedido financeiro, use um contato oficial ou canal independente.'},
    {icon:'shield',title:'Use autenticação em dois fatores',short:'Adicione uma camada extra de proteção.',text:'Quando disponível, habilite autenticação adicional. Métodos que não dependem apenas de SMS podem proteger melhor contas importantes.'},
    {icon:'shopping-bag',title:'Confirme pagamentos na plataforma',short:'Comprovante não é confirmação.',text:'Em marketplaces, use o status dentro da própria plataforma como referência antes de enviar produtos ou pagar taxas.'},
    {icon:'briefcase',title:'Valide vagas e recrutadores',short:'Não pague para ser contratado.',text:'Confira domínio, página de carreiras e processo seletivo. Desconfie de vagas que exigem pagamentos antecipados ou documentos antes de qualquer verificação.'},
    {icon:'receipt',title:'Confira o beneficiário',short:'Logotipo não garante autenticidade.',text:'Em cobranças, compare beneficiário, valor e identificadores com o aplicativo ou portal oficial antes de pagar.'},
    {icon:'refresh',title:'Mantenha aplicativos atualizados',short:'Atualizações corrigem falhas conhecidas.',text:'Instale atualizações por fontes oficiais. Isso não impede engenharia social, mas reduz riscos técnicos evitáveis.'},
    {icon:'user',title:'Proteja dados pessoais',short:'Verifique antes de informar.',text:'Não forneça documentos, credenciais ou dados bancários apenas porque alguém conhece seu nome ou oferece uma oportunidade atraente.'}
  ];

  function init(){window.AntiScamState.load();window.AntiScamUI.initTheme();window.AntiScamIcons.hydrate();window.AntiScamUI.bindDefaultModalEvents();bindNavigation();renderPrevention();refreshHome();window.AntiScamUI.updateHeader();window.AntiScamUI.showScreen('home');}
  function bindNavigation(){
    document.getElementById('brandBtn').addEventListener('click',()=>go('home'));
    document.querySelectorAll('.nav-btn').forEach(btn=>btn.addEventListener('click',()=>go(btn.dataset.screen)));
    document.getElementById('themeBtn').addEventListener('click',window.AntiScamUI.toggleTheme);
    document.getElementById('startChallengeBtn').addEventListener('click',startNextChallenge);document.getElementById('continueBtn').addEventListener('click',continueProgress);
    document.getElementById('exitSimulationBtn').addEventListener('click',()=>go('home'));document.getElementById('hintBtn').addEventListener('click',()=>{if(currentChallenge)modules[currentChallenge]()?.hint?.();});
    document.getElementById('nextChallengeBtn').addEventListener('click',startNextChallenge);document.getElementById('reviewLearningBtn').addEventListener('click',()=>go('learn'));document.getElementById('restartBtn').addEventListener('click',confirmReset);
  }
  function go(screen){currentChallenge=null;if(screen==='home')refreshHome();if(screen==='final')renderFinal();window.AntiScamUI.showScreen(screen);}
  function refreshHome(){const state=window.AntiScamState.getState();const hasIncomplete=order.some(id=>state.challengeData[id]?.started&&!state.completed.includes(id));document.getElementById('continueBtn').classList.toggle('hidden',!hasIncomplete);const startBtn=document.getElementById('startChallengeBtn');startBtn.innerHTML=state.completed.length===TOTAL?`Ver resultado final ${I('arrow-right',17)}`:state.completed.length>0?`Próximo desafio ${I('arrow-right',17)}`:`Começar desafio ${I('arrow-right',17)}`;window.AntiScamUI.updateHeader();}
  function continueProgress(){const state=window.AntiScamState.getState();const candidate=order.find(id=>state.challengeData[id]?.started&&!state.completed.includes(id));candidate?startChallenge(candidate):startNextChallenge();}
  function startNextChallenge(){const state=window.AntiScamState.getState();if(state.completed.length===TOTAL){renderFinal();window.AntiScamUI.showScreen('final');return;}const next=order.find(id=>!state.completed.includes(id));if(next)startChallenge(next);}
  function startChallenge(id){currentChallenge=id;document.getElementById('simulationKicker').textContent=`DESAFIO ${order.indexOf(id)+1} DE ${TOTAL}`;document.getElementById('simulationTitle').textContent=titles[id];window.AntiScamUI.showScreen('simulation');const root=document.getElementById('simulationRoot');root.innerHTML='';const module=modules[id]?.();if(!module){root.innerHTML='<div class="panel-card">Simulação indisponível.</div>';return;}module.start(root);window.AntiScamUI.updateHeader();}
  function showChallengeResult(id,lessons){currentChallenge=null;const summary=window.AntiScamScoring.summaryFor(id),rating=window.AntiScamScoring.rating(summary);document.getElementById('challengeResultIcon').innerHTML=I(rating.icon,34);document.getElementById('challengeResultTitle').textContent=`${names[id]} concluída`;document.getElementById('challengeResultIntro').innerHTML=`Resultado da etapa: <strong class="${rating.className}">${rating.label}</strong>. Segurança também é saber diferenciar suspeita de evidência.`;document.getElementById('challengePoints').textContent=`${summary.points>0?'+':''}${summary.points}`;document.getElementById('challengeSafe').textContent=summary.safe;document.getElementById('challengeRisky').textContent=summary.risky+summary.danger;document.getElementById('challengeEvidence').textContent=summary.evidence;document.getElementById('challengeLessons').innerHTML=`<h3>O que observar na vida real</h3><ul>${lessons.map(item=>`<li>${item}</li>`).join('')}</ul>`;const btn=document.getElementById('nextChallengeBtn');btn.innerHTML=window.AntiScamState.getState().completed.length===TOTAL?`Ver resultado final ${I('arrow-right',17)}`:`Próximo desafio ${I('arrow-right',17)}`;window.AntiScamUI.updateHeader();window.AntiScamUI.showScreen('challenge-result');}
  function renderPrevention(){const grid=document.getElementById('preventionGrid');grid.innerHTML=preventionItems.map((item,index)=>`<button class="prevention-card" data-prevention="${index}"><span class="icon">${I(item.icon,28)}</span><h2>${item.title}</h2><p>${item.short}</p></button>`).join('');grid.querySelectorAll('[data-prevention]').forEach(btn=>btn.addEventListener('click',()=>{const item=preventionItems[Number(btn.dataset.prevention)];window.AntiScamUI.showModal({icon:item.icon,title:item.title,html:item.text,actions:[{label:'Entendi',className:'btn-primary'}]});}));}
  function renderFinal(){
    const state=window.AntiScamState.getState(),max=window.AntiScamState.MAX_SCORE||3000;const score=state.score,perf=window.AntiScamScoring.performance(score),profile=window.AntiScamScoring.profile();const all=window.AntiScamState.getDecisions().filter(d=>!d.meta?.hint&&d.severity!=='neutral');const safe=all.filter(d=>d.severity==='safe').length,risky=all.filter(d=>d.severity==='risky').length,danger=all.filter(d=>d.severity==='danger').length;const totalEvidence=order.reduce((s,id)=>s+window.AntiScamState.getEvidence(id).length,0);const ended=state.completedAt||Date.now();
    document.getElementById('finalScore').textContent=score;document.getElementById('finalScoreMax').textContent=`/${max}`;document.getElementById('scoreRing').style.setProperty('--score-angle',`${Math.round(score/max*360)}deg`);document.getElementById('performanceLabel').textContent=perf.label;document.getElementById('performanceText').textContent=perf.text;document.getElementById('profileBadge').innerHTML=I(profile.icon,32);document.getElementById('profileTitle').textContent=profile.title;document.getElementById('profileText').textContent=profile.text;document.getElementById('cautionIndex').textContent=`${profile.cautionIndex}%`;document.getElementById('cautionBar').style.width=`${profile.cautionIndex}%`;document.getElementById('finalSafe').textContent=safe;document.getElementById('finalRisky').textContent=risky;document.getElementById('finalDanger').textContent=danger;document.getElementById('finalHints').textContent=state.hintsUsed;document.getElementById('finalEvidence').textContent=totalEvidence;document.getElementById('finalTime').textContent=window.AntiScamScoring.formatDuration(ended-state.startedAt);
    document.getElementById('challengeBreakdown').innerHTML=order.map(id=>{const summary=window.AntiScamScoring.summaryFor(id),rating=window.AntiScamScoring.rating(summary);return `<div class="breakdown-item"><div class="breakdown-title"><span>${I(rating.icon,19)}</span><strong>${summary.name}</strong></div><div><span>${summary.points>0?'+':''}${summary.points} pts • ${summary.evidence} evidências</span> <span class="rating-pill ${rating.className}">${rating.label}</span></div></div>`;}).join('');
    document.getElementById('recommendations').innerHTML=window.AntiScamScoring.recommendations().map(text=>`<div class="recommendation-item">${I('arrow-right',17)}<span>${text}</span></div>`).join('');
    const earned=state.achievements.map(id=>({id,...achievements[id]})).filter(x=>x.title);document.getElementById('achievementGrid').innerHTML=earned.length?earned.map(a=>`<article class="achievement-card"><span>${I(a.icon,24)}</span><div><strong>${a.title}</strong><p>${a.text}</p></div></article>`).join(''):`<p class="empty-note">Nenhuma conquista extra nesta rodada. Refazer o desafio pode revelar novos caminhos.</p>`;
    document.getElementById('decisionJourney').innerHTML=all.slice(-24).map(d=>`<div class="journey-item ${d.severity}"><span class="journey-icon">${I(d.severity==='safe'?'circle-check':d.severity==='danger'?'shield-alert':'alert',17)}</span><div><small>${shortLabels[d.challenge]||d.challenge}</small><strong>${d.label}</strong></div><span class="journey-points">${d.points>0?'+':''}${d.points}</span></div>`).join('');
  }
  function confirmReset(){window.AntiScamUI.showModal({icon:'refresh',title:'Reiniciar todo o desafio?',html:'Isso apagará pontuação, decisões, cenários sorteados, evidências, conquistas e pistas salvas <strong>neste navegador</strong>.',actions:[{label:'Cancelar',className:'btn-secondary'},{label:'Sim, reiniciar',icon:'refresh',className:'btn-danger-outline',onClick:()=>{window.AntiScamState.reset();refreshHome();window.AntiScamUI.updateHeader();window.AntiScamUI.showScreen('home');window.AntiScamUI.toast('Desafio reiniciado.','refresh');}}]});}
  window.AntiScamApp={showChallengeResult,startChallenge};document.addEventListener('DOMContentLoaded',init);
})();
