(function(){
  const ID='boleto'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    altered:{type:'fraud',title:'Chegou uma cobrança com vencimento hoje',intro:'Um PDF afirma ser a mensalidade do provedor Nuvem Fibra. O valor parece correto, mas alguns dados merecem atenção.',issuer:'Nuvem Fibra — Treinamento',beneficiary:'R. Pagamentos Online (fictício)',reference:'NF-AGOSTO-8842',evidence:[{id:'beneficiary',label:'Beneficiário não corresponde ao emissor'},{id:'channel',label:'Cobrança chegou por canal diferente do habitual'},{id:'history',label:'Referência diverge do padrão das faturas anteriores'},{id:'pressure',label:'Mensagem ameaça suspensão imediata'}]},
    legit:{type:'legit',title:'Chegou uma cobrança com vencimento hoje',intro:'Uma notificação informa que a mensalidade está disponível. O documento exibe os dados abaixo.',issuer:'Nuvem Fibra — Treinamento',beneficiary:'Nuvem Fibra — Treinamento',reference:'NF-AGOSTO-2026',evidence:[{id:'beneficiary',label:'Beneficiário corresponde ao emissor'},{id:'channel',label:'Cobrança chegou pelo canal habitual da simulação'},{id:'history',label:'Referência segue o padrão das faturas anteriores'},{id:'pressure',label:'Mensagem não usa ameaça fora do aviso de vencimento'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Cobrança, empresa e códigos fictícios</span><span>Desafio 8 de 8 • Boleto/cobrança</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();render();}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="billing-scene"><section class="bill-paper"><div class="bill-logo">${I('receipt',34)} <strong>${scenario.issuer}</strong></div><span class="bill-label">FATURA DE TREINAMENTO</span><h2>Mensalidade de internet</h2><div class="bill-grid"><div><small>Valor</small><strong>R$ 129,90</strong></div><div><small>Vencimento</small><strong>Hoje</strong></div><div><small>Beneficiário</small><strong>${scenario.beneficiary}</strong></div><div><small>Referência</small><strong>${scenario.reference}</strong></div></div><div class="fake-barcode" aria-label="Código de barras fictício"></div><small>Este documento não pode ser pago.</small></section><aside class="billing-message"><span>${I('mail',28)}</span><h3>${scenario.type==='fraud'?'E-mail: “Evite suspensão do serviço”':'Notificação: “Sua fatura está disponível”'}</h3><p>${scenario.type==='fraud'?'“Pague hoje usando o documento anexo para evitar bloqueio imediato.”':'“Sua mensalidade vence hoje. Confira os dados antes do pagamento.”'}</p></aside></div><div class="investigation-layout"><div class="action-panel"><h3>Analise a cobrança antes de classificá-la.</h3><div class="action-grid"><button class="action-btn" id="inspectBeneficiary">${I('user')} Conferir beneficiário</button><button class="action-btn" id="inspectReference">${I('receipt')} Examinar referência e padrão</button><button class="action-btn" id="inspectOrigin">${I('mail')} Analisar origem da cobrança</button><button class="action-btn" id="inspectLanguage">${I('file-text')} Analisar linguagem da mensagem</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectBeneficiary').onclick=beneficiary;document.getElementById('inspectReference').onclick=reference;document.getElementById('inspectOrigin').onclick=origin;document.getElementById('inspectLanguage').onclick=language;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'Beneficiário, referência, origem e pressão não eram coerentes entre si.':'Os dados analisados seguiam um padrão consistente.',incorrectText:scenario.type==='fraud'?'O valor correto sozinho não tornava o documento confiável.':'Nesta rodada, beneficiário e referência eram consistentes com a cobrança.'});
  }
  function beneficiary(){record({action:'inspect-beneficiary',label:'Conferiu o beneficiário da cobrança',severity:'safe',points:60,trait:'investigator'});ev('beneficiary',scenario.type==='fraud'?'Beneficiário não corresponde ao emissor':'Beneficiário corresponde ao emissor');window.AntiScamUI.showModal({icon:'user',title:'Beneficiário',html:`Emissor exibido: <strong>${scenario.issuer}</strong><br>Beneficiário: <strong>${scenario.beneficiary}</strong>`,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function reference(){record({action:'inspect-reference',label:'Comparou referência com histórico fictício',severity:'safe',points:60,trait:'investigator'});ev('history',scenario.type==='fraud'?'Referência diverge do padrão anterior':'Referência segue o padrão anterior');window.AntiScamUI.showModal({icon:'receipt',title:'Histórico fictício',html:scenario.type==='fraud'?'As três faturas anteriores usavam o padrão <strong>NF-MÊS-2026</strong>. O documento atual usa “8842”.':'As faturas anteriores seguem o mesmo padrão de referência e o mesmo beneficiário.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function origin(){record({action:'inspect-origin',label:'Analisou a origem da cobrança',severity:'safe',points:60,trait:'investigator'});ev('channel',scenario.type==='fraud'?'Cobrança chegou por canal diferente do habitual':'Cobrança chegou pelo canal habitual');window.AntiScamUI.showModal({icon:'mail',title:'Origem analisada',html:scenario.type==='fraud'?'O documento veio como anexo de um e-mail novo, enquanto o histórico fictício mostra avisos dentro da área da conta.':'A notificação aparece no mesmo ambiente usado pelas cobranças anteriores da simulação.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function language(){record({action:'inspect-language',label:'Analisou a linguagem da cobrança',severity:'safe',points:60,trait:'investigator'});ev('pressure',scenario.type==='fraud'?'Mensagem ameaça suspensão imediata':'Mensagem apenas informa vencimento');window.AntiScamUI.showModal({icon:'file-text',title:'Linguagem analisada',html:scenario.type==='fraud'?'A mensagem usa “bloqueio imediato” para pressionar pagamento pelo anexo recebido.':'A mensagem informa apenas que a fatura vence hoje e não exige um caminho específico de pagamento.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function finish(){window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['Em cobranças, compare beneficiário, referência, origem e linguagem.','Um valor familiar ou um logotipo convincente não bastam para provar autenticidade.','Procure consistência entre vários elementos antes de tomar uma decisão.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,scenario.type);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Não olhe apenas para o valor. Compare <strong>quem recebe, como a cobrança chegou, o padrão da referência e a linguagem usada</strong>.',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.BoletoSimulation={start,hint};
})();
