(function(){
  const ID='job';let root,scenario;const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    fake:{type:'fraud',title:'Você recebeu uma oferta de emprego inesperada',intro:'Uma recrutadora diz que seu perfil foi “selecionado sem entrevista” e promete salário alto. Para começar, pede pagamento de um curso obrigatório.',company:'Nexa Digital Solutions',sender:'recrutamento.nexa@oportunidade-treino.invalid',evidence:[{id:'domain',label:'Domínio do remetente não combina com a empresa'},{id:'fee',label:'Pagamento é exigido antes da contratação'},{id:'process',label:'Não há entrevista ou etapa de seleção'},{id:'company',label:'Dados apresentados sobre a vaga são inconsistentes'}]},
    legit:{type:'legit',title:'Você recebeu um convite para processo seletivo',intro:'Uma empresa informa que encontrou seu perfil e convida para uma entrevista. Não há promessa de contratação nem cobrança.',company:'Nexa Sistemas — Treinamento',sender:'talentos@nexa-sistemas.local',evidence:[{id:'domain',label:'Domínio do remetente combina com a empresa fictícia'},{id:'fee',label:'Nenhum pagamento é solicitado'},{id:'process',label:'Existem entrevista e etapas claramente descritas'},{id:'company',label:'Cargo, área e processo são coerentes entre si'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Empresa e vaga fictícias</span><span>Desafio 7 de 8 • Vaga de emprego</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();render();}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="job-scene"><section class="job-message"><div class="job-mail-head"><span class="company-avatar">${I('briefcase',26)}</span><div><strong>${scenario.company}</strong><small>${scenario.sender}</small></div></div><span class="job-badge">OPORTUNIDADE PROFISSIONAL</span><h2>${scenario.title}</h2><p>${scenario.intro}</p>${scenario.type==='fraud'?`<div class="offer-box"><strong>Analista Júnior • R$ 8.900/mês</strong><span>Início imediato • sem entrevista</span><span>Curso de integração: R$ 249,00</span></div>`:`<div class="offer-box"><strong>Desenvolvedor Júnior</strong><span>Etapa 1: conversa com recrutamento</span><span>Etapa 2: entrevista técnica</span></div>`}<small class="training-note">${I('shield-alert',15)} Nenhum documento ou pagamento real é solicitado.</small></section><aside class="company-panel"><span>${I('building',38)}</span><h3>${scenario.company}</h3><p>Perfil empresarial fictício para treinamento.</p><div><small>Área</small><strong>Tecnologia e serviços digitais</strong></div></aside></div><div class="investigation-layout"><div class="action-panel"><h3>Investigue a proposta antes de concluir.</h3><div class="action-grid"><button class="action-btn" id="inspectSender">${I('mail')} Examinar remetente e domínio</button><button class="action-btn" id="inspectOffer">${I('briefcase')} Analisar salário e condições</button><button class="action-btn" id="inspectProcess">${I('list-check')} Examinar etapas do processo</button><button class="action-btn" id="inspectCompany">${I('building')} Comparar dados da empresa e da vaga</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectSender').onclick=sender;document.getElementById('inspectOffer').onclick=offer;document.getElementById('inspectProcess').onclick=process;document.getElementById('inspectCompany').onclick=company;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'Remetente, cobrança e ausência de processo formavam um conjunto suspeito.':'A proposta apresentava etapas normais e não exigia pagamento.',incorrectText:scenario.type==='fraud'?'Releia especialmente domínio, cobrança e promessa de contratação imediata.':'Contato inesperado não significa automaticamente fraude; o conjunto desta rodada era coerente.'});
  }
  function sender(){record({action:'inspect-sender',label:'Examinou remetente da vaga',severity:'safe',points:60,trait:'investigator'});ev('domain',scenario.type==='fraud'?'Domínio não combina com a empresa':'Domínio combina com a empresa fictícia');window.AntiScamUI.showModal({icon:'mail',title:'Remetente analisado',html:`Endereço: <strong>${scenario.sender}</strong><br><br>${scenario.type==='fraud'?'O domínio usa um nome genérico de “oportunidade” e não o nome apresentado pela empresa.':'O domínio corresponde ao nome da empresa fictícia exibida na mensagem.'}`,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function offer(){record({action:'inspect-offer',label:'Analisou salário e condições',severity:'safe',points:60,trait:'investigator'});ev('fee',scenario.type==='fraud'?'Pagamento é exigido antes da contratação':'Nenhum pagamento é solicitado');window.AntiScamUI.showModal({icon:'briefcase',title:'Condições analisadas',html:scenario.type==='fraud'?'A proposta promete R$ 8.900 para vaga júnior e exige R$ 249 antes do início.':'A mensagem não promete contratação e não exige compra, curso ou taxa para participar.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function process(){record({action:'inspect-process',label:'Examinou as etapas do processo',severity:'safe',points:60,trait:'investigator'});ev('process',scenario.type==='fraud'?'Não há entrevista ou etapa de seleção':'Existem entrevista e etapas descritas');window.AntiScamUI.showModal({icon:'list-check',title:'Processo analisado',html:scenario.type==='fraud'?'A mensagem afirma que a contratação já está garantida e não descreve nenhuma entrevista.':'A mensagem apresenta conversa inicial e entrevista técnica antes de qualquer contratação.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function company(){record({action:'inspect-company',label:'Comparou dados da empresa e da vaga',severity:'safe',points:60,trait:'investigator'});ev('company',scenario.type==='fraud'?'Dados da vaga e empresa são inconsistentes':'Cargo, área e processo são coerentes');window.AntiScamUI.showModal({icon:'building',title:'Informações comparadas',html:scenario.type==='fraud'?'O nome usado no e-mail, o domínio e a descrição do processo não seguem um padrão consistente.':'Nome da empresa, domínio, cargo e etapas seguem o mesmo padrão dentro da simulação.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function finish(){window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['Em vagas, analise domínio, etapas, salário e qualquer cobrança como um conjunto.','Pagamento antecipado para garantir contratação é uma evidência importante.','Contato inesperado pode ser legítimo; o objetivo é procurar consistência, não rejeitar automaticamente.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,scenario.type);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Compare quatro coisas: <strong>quem enviou, o que promete, quais etapas existem e se há dinheiro envolvido antes da contratação</strong>.',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.JobSimulation={start,hint};
})();
