(function(){
  const ID='marketplace'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    fakeReceipt:{type:'fraud',title:'Você vendeu um notebook em um marketplace',intro:'Um comprador diz que já pagou e envia um “comprovante”. Em seguida pede envio imediato e menciona uma taxa de liberação.',orderStatus:'Aguardando pagamento',buyer:'Carlos • conta criada hoje',evidence:[{id:'app-status',label:'Pedido continua aguardando pagamento'},{id:'receipt',label:'Comprovante foi enviado fora da plataforma'},{id:'fee',label:'Há uma “taxa de liberação” inesperada'},{id:'pressure',label:'Comprador pressiona pelo envio imediato'}]},
    realSale:{type:'legit',title:'Você vendeu um notebook em um marketplace',intro:'O comprador envia uma mensagem agradecendo e a tela do pedido mostra pagamento aprovado e etiqueta disponível.',orderStatus:'Pagamento aprovado • envio autorizado',buyer:'Marina • conta verificada',evidence:[{id:'app-status',label:'Pedido aparece como pago'},{id:'receipt',label:'Não há comprovante externo como prova principal'},{id:'fee',label:'Nenhuma taxa extra é solicitada'},{id:'pressure',label:'Comprador não pressiona por envio fora do fluxo'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Marketplace e compradores fictícios</span><span>Desafio 6 de 8 • Marketplace</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();render();}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="market-scene"><section class="market-dashboard"><div class="market-head"><span>${I('shopping-bag',24)} <strong>TrocaCerta</strong></span><small>ambiente de treinamento</small></div><div class="order-card"><div class="product-thumb">${I('monitor',44)}</div><div><small>Pedido #TR-2048</small><h2>Notebook Orion 14</h2><p>R$ 2.400,00</p><span class="order-status ${scenario.type}">${scenario.orderStatus}</span></div></div><div class="buyer-card"><strong>${scenario.buyer}</strong><p>${scenario.type==='fraud'?'“Já paguei. Confere o comprovante no e-mail e posta hoje. Disseram que falta uma taxa de R$ 79 para liberar seu dinheiro.”':'“Pagamento concluído. Vou acompanhar o rastreio por aqui. Obrigada!”'}</p></div></section><section class="receipt-panel"><div class="receipt-paper"><span>${I('receipt',36)}</span><h3>${scenario.type==='fraud'?'COMPROVANTE RECEBIDO':'RESUMO DO PEDIDO'}</h3><p>${scenario.type==='fraud'?'Arquivo enviado pelo comprador':'Dados exibidos na tela da venda'}</p><div><span>Valor</span><strong>R$ 2.400,00</strong></div><div><span>Status</span><strong>${scenario.type==='fraud'?'Processando liberação':'Aprovado'}</strong></div></div></section></div><div class="investigation-layout"><div class="action-panel"><h3>Procure inconsistências antes de classificar a venda.</h3><div class="action-grid"><button class="action-btn" id="inspectOrder">${I('search')} Examinar status do pedido</button><button class="action-btn" id="inspectReceipt">${I('receipt')} Examinar o comprovante/resumo</button><button class="action-btn" id="inspectBuyer">${I('user')} Analisar a conversa do comprador</button><button class="action-btn" id="inspectFees">${I('credit-card')} Verificar taxas e condições</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectOrder').onclick=order;document.getElementById('inspectReceipt').onclick=receipt;document.getElementById('inspectBuyer').onclick=buyer;document.getElementById('inspectFees').onclick=fees;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'O status do pedido não sustentava a história do comprador.':'Status, conversa e condições eram coerentes com uma venda normal.',incorrectText:scenario.type==='fraud'?'O comprovante isolado não combinava com o estado real do pedido.':'Nesta rodada, a própria tela da venda mostrava consistência entre pagamento e envio.'});
  }
  function order(){record({action:'inspect-order',label:'Examinou o estado do pedido',severity:'safe',points:60,trait:'investigator'});ev('app-status',scenario.type==='fraud'?'Pedido continua aguardando pagamento':'Pedido aparece como pago');window.AntiScamUI.showModal({icon:'shopping-bag',title:'Status do pedido',html:`Na tela do pedido aparece: <strong>${scenario.orderStatus}</strong>.`,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function receipt(){record({action:'inspect-receipt',label:'Examinou o comprovante ou resumo',severity:'safe',points:60,trait:'investigator'});ev('receipt',scenario.type==='fraud'?'Comprovante foi enviado fora da plataforma':'Não há comprovante externo como prova principal');window.AntiScamUI.showModal({icon:'receipt',title:'Origem do documento',html:scenario.type==='fraud'?'O arquivo chegou por e-mail enviado pelo comprador e não aparece anexado ao pedido.':'O resumo faz parte da própria tela do pedido e repete o status “Aprovado”.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function buyer(){record({action:'inspect-buyer',label:'Analisou a conversa do comprador',severity:'safe',points:60,trait:'investigator'});ev('pressure',scenario.type==='fraud'?'Comprador pressiona pelo envio imediato':'Comprador não pressiona por envio fora do fluxo');window.AntiScamUI.showModal({icon:'message',title:'Conversa analisada',html:scenario.type==='fraud'?'O comprador insiste em postagem imediata e tenta usar o comprovante como argumento para acelerar sua decisão.':'A conversa apenas acompanha o pedido e não solicita mudanças no fluxo de pagamento ou envio.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function fees(){record({action:'inspect-fees',label:'Verificou taxas e condições da venda',severity:'safe',points:60,trait:'investigator'});ev('fee',scenario.type==='fraud'?'Há taxa inesperada para “liberar” o valor':'Nenhuma taxa extra é solicitada');window.AntiScamUI.showModal({icon:'credit-card',title:'Taxas e condições',html:scenario.type==='fraud'?'A mensagem menciona R$ 79 para “liberar” um dinheiro que nem aparece como pago no pedido.':'Não existe cobrança adicional ligada à liberação do pagamento.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function finish(){window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['Comprovantes enviados por terceiros não devem ser analisados isoladamente.','Compare conversa, status do pedido e condições da venda procurando contradições.','Pressão para enviar e taxas inesperadas são evidências importantes quando aparecem juntas.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,scenario.type);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Compare a história do comprador com o que a própria tela do pedido mostra. <strong>Os dois lados contam a mesma história?</strong>',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.MarketplaceSimulation={start,hint};
})();
