(function () {
  const ID='phishing'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    'bank-fraud':{type:'fraud',senderName:'Segurança • Banco Aurora',sender:'seguranca@banc0-aurora.com',subject:'ATENÇÃO: sua conta será bloqueada',preview:'Detectamos uma atividade incomum...',header:'BANCO AURORA • Central de Segurança',body:'Detectamos uma atividade incomum em sua conta. Por segurança, seu acesso será <strong>bloqueado nas próximas 2 horas</strong> caso a verificação não seja concluída.',cta:'Verificar minha conta',link:'https://seguranca-aurora-conta.exemplo/confirmar',fakeAddress:'seguranca-aurora-conta.exemplo/confirmar',fakeBrand:'Banco Aurora',senderClue:'O domínio usa <strong>banc0</strong>, com o número zero no lugar da letra “o”.',linkClue:'O botão aponta para um endereço diferente do nome do serviço apresentado na mensagem.',evidence:[{id:'urgency',label:'Mensagem pressiona para agir em até 2 horas'},{id:'sender',label:'Domínio do remetente tem alteração sutil'},{id:'link',label:'Destino do botão não combina com o serviço'},{id:'request',label:'Mensagem pede ação sensível pelo próprio link'}]},
    'cloud-fraud':{type:'fraud',senderName:'Equipe de Conta • Nuvem Atlas',sender:'suporte@nuvem-atlas-acesso.exemplo',subject:'Armazenamento suspenso — ação necessária',preview:'Seus arquivos poderão ser removidos...',header:'NUVEM ATLAS • Aviso de armazenamento',body:'Não conseguimos validar sua assinatura. Seus arquivos poderão ser <strong>removidos ainda hoje</strong> se a conta não for reativada.',cta:'Reativar armazenamento',link:'https://nuvem-atlas-acesso.exemplo/reativar',fakeAddress:'nuvem-atlas-acesso.exemplo/reativar',fakeBrand:'Nuvem Atlas',senderClue:'O remetente usa um domínio adicional “<strong>-acesso</strong>”, diferente do nome simples do serviço.',linkClue:'O endereço do botão é parecido com o serviço, mas contém palavras extras.',evidence:[{id:'urgency',label:'Mensagem ameaça remoção “ainda hoje”'},{id:'sender',label:'Domínio é parecido, mas diferente'},{id:'link',label:'Link usa endereço com palavras extras'},{id:'request',label:'Reativação é exigida diretamente pelo e-mail'}]},
    'legit-bank':{type:'legit',senderName:'Avisos • Banco Aurora',sender:'avisos@bancoaurora.exemplo',subject:'Seu extrato mensal está disponível',preview:'Consulte pelo aplicativo Banco Aurora...',header:'BANCO AURORA • Aviso de conta',body:'Seu extrato mensal já está disponível. Este e-mail não solicita senha, código ou atualização cadastral.',cta:null,link:null,fakeAddress:null,fakeBrand:'Banco Aurora',senderClue:'O endereço usa <strong>bancoaurora.exemplo</strong>, sem troca de letras ou palavras extras.',linkClue:'A mensagem <strong>não contém link</strong>, botão de login ou formulário.',evidence:[{id:'sender',label:'Remetente e domínio são coerentes'},{id:'no-link',label:'Mensagem não contém link externo'},{id:'no-data',label:'Nenhum dado, senha ou código é solicitado'},{id:'no-urgency',label:'Não há ameaça ou pressão para agir imediatamente'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);
  function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  function setStage(v){window.AntiScamState.setChallengeValue(ID,'stage',v);} const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];
  const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Simulação educativa • Serviços e endereços fictícios</span><span>Desafio 1 de 8 • E-mail</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();const stage=window.AntiScamState.getChallengeValue(ID,'stage','inbox');stage==='login'&&scenario.type==='fraud'?renderFakeLogin():stage==='email'?renderEmail():renderInbox();}
  function renderInbox(){setStage('inbox');root.innerHTML=`<div class="sim-frame">${meta()}<div class="mail-app"><aside class="mail-sidebar"><div class="mail-brand">${I('mail',18)} Nebula Mail</div><button class="mail-compose" disabled>${I('mail',16)} Nova mensagem</button><div class="mail-folder active"><span>Caixa de entrada</span><strong>2</strong></div><div class="mail-folder"><span>Favoritos</span><span>0</span></div><div class="mail-folder"><span>Enviados</span></div></aside><section class="mail-list" aria-label="Caixa de entrada simulada"><div class="mail-topbar"><input class="mail-search" value="Pesquisar e-mails" readonly><span>${I('settings',18)}</span></div><button class="email-row unread" id="scenarioEmail"><span>${I('star',15)}</span><span class="sender">${scenario.senderName}</span><span>${scenario.subject} <span class="preview">— ${scenario.preview}</span></span><time>23:41</time></button><div class="email-row"><span>${I('star',15)}</span><span class="sender">Faculdade Fasipe - Administrativo</span><span>Calendário acadêmico <span class="preview">— Confira as datas da próxima semana...</span></span><time>18:20</time></div></section></div><div class="investigation-layout"><div class="action-panel"><h3>Uma mensagem chamou sua atenção.</h3><div class="action-grid"><button class="action-btn" id="openEmailBtn">${I('eye')} Abrir a mensagem</button></div></div>${evidenceSlot()}</div></div>`;document.getElementById('scenarioEmail').onclick=renderEmail;document.getElementById('openEmailBtn').onclick=renderEmail;}
  function renderEmail(){setStage('email');const cta=scenario.cta?`<button class="fake-bank-button" id="verifyAccountBtn">${scenario.cta}</button>`:`<div class="legit-no-link">${I('shield',18)} Nenhum link foi incluído nesta mensagem.</div>`;root.innerHTML=`<div class="sim-frame">${meta()}<div class="email-open"><div class="email-open-toolbar"><button class="email-tool" id="backInbox">${I('arrow-left',15)} Voltar</button></div><article class="email-content"><h2>${scenario.subject}</h2><div class="sender-line"><div class="sender-avatar">${scenario.senderName.charAt(0)}</div><div class="sender-info"><strong>${scenario.senderName}</strong><small>de <span class="sender-address" id="senderAddress" tabindex="0">${scenario.sender}</span></small></div></div><div class="fake-bank-mail"><div class="fake-bank-head">${scenario.header}</div><div class="fake-bank-body"><p>Olá,</p><p>${scenario.body}</p>${cta}<p>Mensagem automática de treinamento.</p><div id="linkPreview" class="mail-link-preview hidden"></div></div></div></article></div><div class="investigation-layout"><div class="action-panel"><h3>Procure sinais sem decidir ainda.</h3><div class="action-grid"><button class="action-btn" id="inspectSender">${I('mail')} Examinar remetente</button><button class="action-btn" id="inspectLink">${I('link')} Examinar links</button><button class="action-btn" id="inspectLanguage">${I('file-text')} Analisar linguagem</button><button class="action-btn" id="inspectRequest">${I('list-check')} Identificar o que a mensagem pede</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('backInbox').onclick=renderInbox;document.getElementById('inspectSender').onclick=inspectSender;document.getElementById('inspectLink').onclick=inspectLink;document.getElementById('inspectLanguage').onclick=inspectLanguage;document.getElementById('inspectRequest').onclick=inspectRequest;document.getElementById('verifyAccountBtn')?.addEventListener('click',clickLink);
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'Remetente, pressão e destino do link formavam um conjunto incompatível.':'Ausência de pressão, links e pedidos sensíveis sustentava a legitimidade.',incorrectText:scenario.type==='fraud'?'Revise as pequenas diferenças no remetente e no destino do botão.':'Nesta rodada faltavam os principais sinais de engenharia social.'});
  }
  function inspectSender(){record({action:'inspect-sender',label:'Examinou o endereço do remetente',severity:'safe',points:60,trait:'investigator'});ev('sender',scenario.type==='fraud'?'Domínio do remetente analisado':'Remetente e domínio coerentes');window.AntiScamUI.showModal({icon:'mail',title:'Remetente analisado',html:scenario.senderClue,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function inspectLink(){record({action:'inspect-link',label:'Examinou links da mensagem',severity:'safe',points:60,trait:'investigator'});const preview=document.getElementById('linkPreview');if(scenario.type==='fraud'){ev('link','Destino do botão analisado');if(preview){preview.classList.remove('hidden');preview.innerHTML=`Destino do botão: <strong>${scenario.link}</strong><br>Endereço fictício e não navegável.`;}window.AntiScamUI.achievement('analista-links','Analista de Links');}else{ev('no-link','Ausência de link externo confirmada');if(preview){preview.classList.remove('hidden');preview.innerHTML='A mensagem não contém links externos.';}}window.AntiScamUI.showModal({icon:'link',title:'Links analisados',html:scenario.linkClue,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function inspectLanguage(){record({action:'inspect-language',label:'Analisou a linguagem da mensagem',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'urgency':'no-urgency',scenario.type==='fraud'?'Pressão temporal identificada':'Ausência de pressão identificada');window.AntiScamUI.showModal({icon:'file-text',title:'Linguagem analisada',html:scenario.type==='fraud'?'A mensagem combina ameaça de bloqueio/perda com prazo curto para provocar uma decisão rápida.':'O texto apenas informa a disponibilidade de um extrato, sem ameaça ou prazo urgente.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function inspectRequest(){record({action:'inspect-request',label:'Identificou o pedido central da mensagem',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'request':'no-data',scenario.type==='fraud'?'Ação sensível solicitada pelo e-mail':'Nenhum dado ou código solicitado');window.AntiScamUI.showModal({icon:'list-check',title:'Pedido identificado',html:scenario.type==='fraud'?'A mensagem quer que a própria mensagem seja o caminho para “verificar” ou “reativar” a conta.':'A mensagem não pede senha, código, atualização cadastral ou formulário.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function clickLink(){record({action:'click-message-link',label:'Abriu o botão da mensagem durante a análise',severity:'risky',points:-35,trait:'impulsive'});setStage('login');renderFakeLogin();}
  function renderFakeLogin(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="fake-browser"><div class="browser-bar"><div class="traffic-lights"><span></span><span></span><span></span></div><div class="address-bar">${I('lock',15)} ${scenario.fakeAddress}</div></div><div class="fake-login-wrap"><div class="fake-login-card"><strong>${scenario.fakeBrand}</strong><h2>Confirme sua conta</h2><p>Entre para continuar.</p><label>Usuário fictício</label><input value="USUARIO-DE-TREINO" readonly><label>Senha fictícia</label><input value="NAO-DIGITE-DADOS-REAIS" readonly><button class="fake-bank-button" disabled>Confirmar dados fictícios</button><div class="training-note">${I('shield-alert',16)} Treinamento: nenhum dado real é aceito.</div></div></div></div><div class="investigation-layout"><div class="action-panel"><h3>A página abriu. Continue procurando evidências.</h3><div class="action-grid"><button class="action-btn" id="inspectAddress">${I('search')} Examinar endereço</button><button class="action-btn" id="inspectForm">${I('file-text')} Examinar o que o formulário pede</button><button class="action-btn" id="backEmail">${I('arrow-left')} Voltar ao e-mail</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectAddress').onclick=()=>{record({action:'inspect-page-address',label:'Examinou o endereço da página aberta',severity:'safe',points:60,trait:'investigator'});ev('link','Endereço da página não combina com o serviço');window.AntiScamUI.showModal({icon:'search',title:'Endereço analisado',html:`A barra mostra <strong>${scenario.fakeAddress}</strong>. O visual da página não altera o endereço onde ela está hospedada.`,actions:[{label:'Continuar',className:'btn-primary'}]});};
    document.getElementById('inspectForm').onclick=()=>{record({action:'inspect-form',label:'Examinou o formulário da página',severity:'safe',points:60,trait:'investigator'});ev('request','Página solicita credenciais para continuar');window.AntiScamUI.showModal({icon:'file-text',title:'Formulário analisado',html:'A página pede usuário e senha imediatamente após um link recebido por e-mail. Os campos são bloqueados nesta simulação.',actions:[{label:'Continuar',className:'btn-primary'}]});};document.getElementById('backEmail').onclick=renderEmail;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:'fraud',onFinish:finish,correctText:'Mesmo depois do clique, endereço e formulário ainda forneciam evidências para interromper a ação.',incorrectText:'O visual semelhante ao serviço não compensa o endereço e o pedido de credenciais.'});
  }
  function finish(){if(window.AntiScamState.getEvidence(ID).length>=3)window.AntiScamUI.achievement('sem-pressa','Sem Pressa');window.AntiScamState.completeChallenge(ID);setStage('done');window.AntiScamApp.showChallengeResult(ID,['Compare remetente, link, linguagem e pedido antes de classificar um e-mail.','Urgência é uma pista, não uma prova isolada.','Páginas convincentes ainda podem estar em endereços diferentes do serviço que imitam.']);}
  function hint(){const stage=window.AntiScamState.getChallengeValue(ID,'stage','inbox');const used=window.AntiScamState.useHint(ID,`${scenario.type}-${stage}`);window.AntiScamUI.updateHeader();const text=scenario.type==='legit'?'Procure também pelo que <strong>não existe</strong>: link, urgência, pedido de senha ou código.':stage==='login'?'Olhe para <strong>o endereço da página e o que o formulário pede</strong>, não apenas para o logotipo.':'Compare <strong>remetente, destino do link, pressão e pedido central</strong>.';window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:text,actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.PhishingSimulation={start,hint};
})();
