(function(){
  const ID='qrcode'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    overlay:{type:'fraud',title:'Um QR Code apareceu no parquímetro',intro:'Você estacionou e encontrou um adesivo com “Pague pelo QR Code — evite multa”.',destination:'pague-agora.estacionamento-treino.invalid',beneficiary:'M. Serviços Digitais (fictício)',evidence:[{id:'sticker',label:'Há sinais de adesivo sobreposto'},{id:'domain',label:'Destino do QR não combina com o serviço'},{id:'beneficiary',label:'Beneficiário não corresponde ao estacionamento'},{id:'amount',label:'Informações do QR divergem do painel'}]},
    official:{type:'legit',title:'Um QR Code apareceu no parquímetro',intro:'O equipamento informa pagamento por QR Code e mostra o mesmo código no visor interno.',destination:'pagamento.estaciona.local (fictício)',beneficiary:'Estaciona Cidade — Treinamento',evidence:[{id:'built-in',label:'QR também aparece no visor do equipamento'},{id:'domain',label:'Destino combina com o serviço fictício'},{id:'beneficiary',label:'Beneficiário corresponde ao estacionamento'},{id:'amount',label:'Valor e local coincidem com o painel'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);
  function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];
  const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;
  function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}
  function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Simulação educativa • QR e endereços fictícios</span><span>Desafio 4 de 8 • QR Code</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();render();}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="generic-scene"><section class="scene-context"><span class="section-kicker">PAGAMENTO NO MUNDO FÍSICO</span><h2>${scenario.title}</h2><p>${scenario.intro}</p><div class="timeline-list"><div class="timeline-item">${I('qr-code',16)} O código abre uma tela de pagamento.</div><div class="timeline-item">${I('info',16)} Nesta simulação, um QR pode ser verdadeiro ou adulterado.</div></div></section><div class="prop-stage"><div class="parking-meter"><div class="meter-head">ESTACIONA <small>treinamento</small></div><div class="meter-screen">Vaga 27<br><strong>R$ 8,00</strong></div><div class="qr-card ${scenario.type==='fraud'?'sticker-overlay':''}"><div class="fake-qr" aria-label="Representação fictícia de QR Code"></div><strong>PAGUE AQUI</strong><small>Escaneie para continuar</small></div><div class="meter-foot">Setor Centro • vaga 27</div></div></div></div><div class="investigation-layout"><div class="action-panel"><h3>Procure evidências antes de concluir.</h3><div class="action-grid"><button class="action-btn" id="inspectSticker">${I('search')} Examinar o QR fisicamente</button><button class="action-btn" id="scanPreview">${I('qr-code')} Visualizar destino do QR</button><button class="action-btn" id="inspectPayment">${I('receipt')} Conferir beneficiário e valor</button><button class="action-btn" id="comparePanel">${I('list-check')} Comparar com o painel</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectSticker').onclick=inspectSticker;document.getElementById('scanPreview').onclick=scan;document.getElementById('inspectPayment').onclick=payment;document.getElementById('comparePanel').onclick=compare;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'As pistas apontavam para um QR adulterado.':'As pistas eram coerentes entre si e não mostravam adulteração.',incorrectText:scenario.type==='fraud'?'Revise principalmente o adesivo, o destino e o beneficiário.':'Nesta rodada, destino, beneficiário e painel eram coerentes.'});
  }
  function inspectSticker(){record({action:'inspect-sticker',label:'Examinou o QR fisicamente',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'sticker':'built-in',scenario.type==='fraud'?'Bordas indicam adesivo sobreposto':'QR também aparece no visor interno');window.AntiScamUI.showModal({icon:'search',title:'Inspeção física',html:scenario.type==='fraud'?'Você percebe uma borda irregular e uma camada colada por cima da área original do equipamento.':'O código não aparece apenas em um adesivo: o mesmo padrão é mostrado no visor interno do equipamento.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function scan(){record({action:'preview-qr',label:'Visualizou o destino do QR',severity:'safe',points:60,trait:'investigator'});ev('domain',scenario.type==='fraud'?'Destino não combina com o serviço':'Destino combina com o serviço fictício');window.AntiScamUI.showModal({icon:'qr-code',title:'Prévia do destino',html:`Endereço fictício: <strong>${scenario.destination}</strong><br><br>${scenario.type==='fraud'?'O nome do endereço não combina com o serviço exibido no parquímetro.':'O endereço é coerente com o nome do serviço fictício mostrado no equipamento.'}`,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function payment(){record({action:'inspect-payment',label:'Conferiu beneficiário e valor',severity:'safe',points:60,trait:'investigator'});ev('beneficiary',scenario.type==='fraud'?'Beneficiário não corresponde ao estacionamento':'Beneficiário corresponde ao estacionamento');window.AntiScamUI.showModal({icon:'receipt',title:'Dados do pagamento',html:`Beneficiário: <strong>${scenario.beneficiary}</strong><br>Valor: <strong>R$ 8,00</strong>`,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function compare(){record({action:'compare-panel',label:'Comparou o QR com as informações do equipamento',severity:'safe',points:60,trait:'investigator'});ev('amount',scenario.type==='fraud'?'Informações do QR divergem do painel':'Valor e local coincidem com o painel');window.AntiScamUI.showModal({icon:'list-check',title:'Comparação concluída',html:scenario.type==='fraud'?'A tela vinculada ao QR não identifica a vaga 27 nem o serviço exibido no equipamento.':'A tela vinculada ao QR repete o valor, o setor e a vaga mostrados no equipamento.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function finish(){window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['QR Codes podem ser substituídos fisicamente por adesivos falsos.','Antes de pagar, observe destino, valor e beneficiário exibidos na prévia.','Compare várias evidências; um único detalhe isolado nem sempre prova fraude.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,scenario.type);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Olhe para o QR como um objeto e como um endereço: <strong>há sobreposição, o destino combina e quem receberá o dinheiro?</strong>',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.QRCodeSimulation={start,hint};
})();
