(function(){
  const challengeNames={phishing:'Phishing',simswap:'SIM Swap',whatsapp:'Perfil falso',qrcode:'QR Code falso',support:'Falso suporte técnico',marketplace:'Golpe em marketplace',job:'Vaga de emprego falsa',boleto:'Cobrança/boleto falso'};
  function summaryFor(challenge){const decisions=window.AntiScamState.getDecisions(challenge);const relevant=decisions.filter(d=>!d.meta?.hint&&d.severity!=='neutral');const points=decisions.reduce((s,d)=>s+d.points,0);const safe=relevant.filter(d=>d.severity==='safe').length,risky=relevant.filter(d=>d.severity==='risky').length,danger=relevant.filter(d=>d.severity==='danger').length,hints=decisions.filter(d=>d.meta?.hint).length;const positive=decisions.filter(d=>d.points>0).reduce((s,d)=>s+d.points,0),negative=Math.abs(decisions.filter(d=>d.points<0).reduce((s,d)=>s+d.points,0));const quality=Math.max(0,Math.min(100,Math.round((positive/Math.max(1,positive+negative))*100)));return{challenge,name:challengeNames[challenge]||challenge,points,safe,risky,danger,hints,quality,evidence:window.AntiScamState.getEvidence(challenge).length};}
  function rating(summary){if(summary.danger>0||summary.quality<45)return{label:'Precisa revisar',className:'rating-risk',icon:'alert'};if(summary.risky>0||summary.hints>1||summary.quality<75)return{label:'Atenção',className:'rating-watch',icon:'search'};return{label:'Excelente',className:'rating-good',icon:'shield'};}
  function performance(score){const max=window.AntiScamState.MAX_SCORE||3000,p=score/max;if(p>=.80)return{label:'EXCELENTE',text:'Você demonstrou atenção consistente, encontrou evidências diferentes e evitou concluir com base em um único sinal.'};if(p>=.60)return{label:'BOM',text:'Você tomou boas decisões em vários tipos de golpe, mas alguns sinais e falsos positivos ainda podem ser melhor avaliados.'};if(p>=.35)return{label:'EM DESENVOLVIMENTO',text:'Você reconheceu parte dos alertas, porém algumas decisões rápidas aumentaram o risco em cenários diferentes.'};return{label:'ATENÇÃO',text:'Vale revisar os sinais básicos e praticar a comparação de evidências antes de concluir.'};}
  function profile(){const decisions=window.AntiScamState.getDecisions().filter(d=>!d.meta?.hint);const traits={cautious:0,investigator:0,impulsive:0};decisions.forEach(d=>{if(traits[d.trait]!==undefined)traits[d.trait]+=Math.max(1,Math.abs(d.points));});const top=Object.entries(traits).sort((a,b)=>b[1]-a[1])[0]?.[0]||'cautious';const safe=decisions.filter(d=>d.severity==='safe').length,risky=decisions.filter(d=>d.severity==='risky'||d.severity==='danger').length,cautionIndex=Math.max(0,Math.min(100,Math.round((safe/Math.max(1,safe+risky))*100)));if(top==='investigator')return{icon:'search',title:'Investigador',text:'Você tende a procurar detalhes, comparar sinais e testar hipóteses antes de concluir.',cautionIndex};if(top==='impulsive')return{icon:'alert',title:'Impulsivo',text:'Na simulação, você agiu rapidamente em alguns momentos. Urgência, dinheiro e pedidos inesperados merecem uma verificação extra.',cautionIndex};return{icon:'shield',title:'Cauteloso',text:'Você tende a reunir contexto e evidências antes de decisões importantes.',cautionIndex};}
  function recommendations(){const result=[];const messages={
    phishing:'No e-mail, compare remetente, domínio e destino do link antes de agir.',simswap:'Ao perder sinal, procure evidências adicionais e confirme com a operadora por canal oficial.',whatsapp:'Confirme números novos por outro canal antes de dinheiro, códigos ou dados.',qrcode:'Antes de pagar por QR Code, confira destino, beneficiário e sinais de adesivo sobreposto.',support:'Não trate pop-ups como diagnóstico do sistema; verifique a central de segurança oficial.',marketplace:'Confirme venda e pagamento dentro do marketplace antes de enviar produtos ou pagar taxas.',job:'Valide vagas no site oficial e desconfie de pagamentos para garantir contratação.',boleto:'Confira beneficiário e compare a cobrança com o portal oficial antes de pagar.'};
    (window.AntiScamState.CHALLENGES||Object.keys(messages)).forEach(id=>{const s=summaryFor(id);if(s.risky+s.danger>0)result.push(messages[id]);});
    if(!result.length)result.push('Você verificou bem os diferentes cenários. Continue usando fontes independentes e canais oficiais antes de decisões sensíveis.');
    if(window.AntiScamState.getState().hintsUsed>=3)result.push('Refaça alguns desafios usando menos pistas para praticar a identificação independente dos sinais.');
    return result.slice(0,8);
  }
  function formatDuration(ms){if(!Number.isFinite(ms)||ms<0)return'—';const total=Math.max(1,Math.round(ms/1000)),min=Math.floor(total/60),sec=total%60;return min?`${min} min ${String(sec).padStart(2,'0')} s`:`${sec} s`;}
  window.AntiScamScoring={summaryFor,rating,performance,profile,recommendations,formatDuration};
})();
