(function(){
  const ID='simswap'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    attack:{type:'fraud',title:'Seu celular ficou sem serviço.',intro:'O sinal desapareceu de repente e, pelo Wi‑Fi, chegaram alertas de segurança que você não reconhece.',alerts:[{app:'Conta Nuvem',title:'Nova tentativa de acesso',text:'Uma redefinição de senha foi solicitada em um dispositivo não reconhecido.'},{app:'Carteira Lumen',title:'Configuração de segurança alterada',text:'Um método de recuperação foi modificado.'},{app:'Mensagens',title:'Conecta Mobile',text:'“Regularize sua linha agora para reativar o sinal.”'}],evidence:[{id:'signal',label:'Perda repentina de sinal'},{id:'accounts',label:'Alterações em contas ocorreram no mesmo período'},{id:'sms',label:'Mensagem usa urgência e link externo'},{id:'timing',label:'Vários eventos suspeitos começaram quase juntos'}]},
    outage:{type:'legit',title:'Seu celular ficou sem serviço.',intro:'O sinal desapareceu, mas até agora nenhuma conta importante apresenta alterações desconhecidas.',alerts:[{app:'Conta Nuvem',title:'Nenhum alerta recente',text:'Último acesso reconhecido há 3 horas.'},{app:'Carteira Lumen',title:'Segurança normal',text:'Nenhuma alteração de recuperação registrada.'},{app:'Sistema',title:'Wi‑Fi conectado',text:'Chamadas e dados móveis indisponíveis no momento.'}],evidence:[{id:'signal',label:'Perda repentina de sinal'},{id:'no-account-change',label:'Contas não mostram alterações desconhecidas'},{id:'area',label:'Outro aparelho da mesma rede também está sem sinal'},{id:'timing',label:'Não há outros eventos de segurança no mesmo período'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Simulação educativa • Operadora e contas fictícias</span><span>Desafio 2 de 8 • Linha móvel</span></div>`;}
  function context(){return `<section class="scene-context"><span class="section-kicker">23:48 • SITUAÇÃO INESPERADA</span><h2>${scenario.title}</h2><p>${scenario.intro}</p><div class="timeline-list"><div class="timeline-item alert">${I('wifi-off',16)} “Sem serviço” apareceu sem explicação.</div></div></section>`;}
  function phone(){return `<div class="phone-stage"><div class="phone-shell"><div class="phone-status"><span>23:48</span><span class="no-service">Sem serviço • Wi‑Fi</span><span>72%</span></div><div class="phone-home"><div class="phone-time"><strong>23:48</strong><span>Sexta-feira</span></div>${scenario.alerts.map((a,i)=>`<div class="notification"><div class="notification-head"><span>${a.app.toUpperCase()}</span><span>${i?'2 min':'agora'}</span></div><strong>${a.title}</strong><p>${a.text}</p></div>`).join('')}<div class="phone-dock"><div class="app-icon"><span>${I('phone',19)}</span>Telefone</div><div class="app-icon"><span>${I('mail',19)}</span>Mensagens</div><div class="app-icon"><span>${I('wallet',19)}</span>Carteira</div><div class="app-icon"><span>${I('settings',19)}</span>Ajustes</div></div></div></div></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();ev('signal','Perda repentina de sinal');render();}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="mobile-scene">${context()}${phone()}</div><div class="investigation-layout"><div class="action-panel"><h3>Procure sinais que expliquem o que está acontecendo.</h3><div class="action-grid"><button class="action-btn" id="inspectAccounts">${I('lock')} Examinar alertas das contas</button><button class="action-btn" id="inspectMessage">${I('mail')} Examinar mensagens recentes</button><button class="action-btn" id="inspectArea">${I('network')} Comparar com outro aparelho próximo</button><button class="action-btn" id="inspectTimeline">${I('clock')} Organizar a linha do tempo</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectAccounts').onclick=accounts;document.getElementById('inspectMessage').onclick=message;document.getElementById('inspectArea').onclick=area;document.getElementById('inspectTimeline').onclick=timeline;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'A perda de sinal veio acompanhada de mudanças em contas e mensagem suspeita.':'A perda de sinal apareceu isolada, sem alterações de contas e atingindo outro aparelho próximo.',incorrectText:scenario.type==='fraud'?'Perda de sinal sozinha é ambígua; nesta rodada os eventos paralelos eram o ponto decisivo.':'Nesta rodada não havia sinais de tomada de contas ou tentativa de direcionamento.'});
  }
  function accounts(){record({action:'inspect-accounts',label:'Examinou alertas das contas',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'accounts':'no-account-change',scenario.type==='fraud'?'Alterações em contas ocorreram no mesmo período':'Contas não mostram alterações desconhecidas');window.AntiScamUI.showModal({icon:'lock',title:'Contas analisadas',html:scenario.type==='fraud'?'<strong>Conta Nuvem:</strong> redefinição solicitada.<br><strong>Carteira Lumen:</strong> recuperação alterada.<br><br>As mudanças ocorreram poucos minutos após a perda do sinal.':'Os últimos acessos são reconhecidos e não há mudança de senha, recuperação ou dispositivo nas contas exibidas.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function message(){record({action:'inspect-messages',label:'Examinou mensagens recentes',severity:'safe',points:60,trait:'investigator'});if(scenario.type==='fraud'){ev('sms','Mensagem usa urgência e link externo');window.AntiScamUI.showModal({icon:'mail',title:'Mensagem encontrada',html:'“Regularize sua linha agora para reativar o sinal: <strong>conecta-validacao.exemplo/linha</strong>”.<br><br>O remetente não está verificado e a mensagem explora exatamente a perda de sinal.',actions:[{label:'Continuar',className:'btn-primary'}]});}else{ev('timing','Não há outros eventos de segurança no mesmo período');window.AntiScamUI.showModal({icon:'mail',title:'Mensagens analisadas',html:'Não há SMS de recuperação, links, avisos de troca de senha ou mensagens relacionadas à perda de sinal.',actions:[{label:'Continuar',className:'btn-primary'}]});}}
  function area(){record({action:'compare-area',label:'Comparou o sinal com outro aparelho próximo',severity:'safe',points:60,trait:'investigator'});if(scenario.type==='fraud'){ev('timing','Seu aparelho é o único da casa sem serviço');window.AntiScamUI.showModal({icon:'network',title:'Comparação local',html:'Outro celular da mesma operadora, no mesmo local, continua com sinal normal.',actions:[{label:'Continuar',className:'btn-primary'}]});}else{ev('area','Outro aparelho da mesma rede também está sem sinal');window.AntiScamUI.showModal({icon:'network',title:'Comparação local',html:'Outro celular da mesma operadora, no mesmo ambiente, também está sem serviço.',actions:[{label:'Continuar',className:'btn-primary'}]});}}
  function timeline(){record({action:'inspect-timeline',label:'Organizou a linha do tempo dos eventos',severity:'safe',points:60,trait:'investigator'});ev('timing',scenario.type==='fraud'?'Vários eventos suspeitos começaram quase juntos':'Não há outros eventos de segurança no mesmo período');window.AntiScamUI.showModal({icon:'clock',title:'Linha do tempo',html:scenario.type==='fraud'?'23:46 sinal perdido → 23:47 redefinição de senha → 23:48 recuperação alterada → 23:49 SMS urgente.':'23:46 sinal perdido → 23:48 contas normais → 23:50 segundo aparelho próximo também sem sinal. Nenhuma alteração de segurança aparece.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function finish(){if(window.AntiScamState.getEvidence(ID).length>=3)window.AntiScamUI.achievement('investigador-de-sinais','Investigador de Sinais');window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['Perda inesperada de sinal é um alerta, mas não prova sozinha um SIM Swap.','Procure eventos paralelos: alterações em contas, mensagens de recuperação e diferenças entre aparelhos próximos.','Quanto mais sinais independentes coincidem no tempo, mais forte fica a hipótese de comprometimento.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,scenario.type);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Não tente explicar tudo apenas pelo ícone “Sem serviço”. Compare <strong>contas, mensagens, outros aparelhos e horário dos eventos</strong>.',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.SimSwapSimulation={start,hint};
})();
