(function(){
  const ID='support'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    scare:{type:'fraud',title:'Um alerta tomou conta do navegador',intro:'Uma página afirma que seu computador está infectado e manda ligar imediatamente para “Suporte Certificado”.',origin:'alerta-seguranca-treino.invalid',evidence:[{id:'browser',label:'Alerta está dentro de uma página do navegador'},{id:'phone',label:'Mensagem exige ligação para um número exibido por ela'},{id:'remote',label:'Texto menciona acesso remoto ao computador'},{id:'pressure',label:'Aviso usa urgência e ameaça de perda de arquivos'}]},
    update:{type:'legit',title:'O sistema exibe uma atualização de segurança',intro:'Uma notificação discreta informa que há uma atualização disponível nas configurações do dispositivo.',origin:'Configurações do sistema',evidence:[{id:'system-origin',label:'Aviso veio das configurações locais'},{id:'no-phone',label:'Nenhum telefone ou pagamento é solicitado'},{id:'update',label:'Mensagem informa versão e tamanho da atualização'},{id:'no-pressure',label:'Não há ameaça para impedir o fechamento da tela'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Simulação educativa • Nenhum suporte real é acionado</span><span>Desafio 5 de 8 • Suporte técnico</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();render();}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="desktop-scene"><div class="desktop-browser"><div class="browser-bar"><div class="traffic-lights"><span></span><span></span><span></span></div><div class="address-bar">${scenario.origin}</div></div><div class="support-page ${scenario.type}">${scenario.type==='fraud'?`<div class="scare-icon">${I('shield-alert',52)}</div><h2>AMEAÇA CRÍTICA DETECTADA</h2><p>Não feche esta janela. Seus arquivos podem estar em risco.</p><div class="support-number">Ligue agora: 0800-000-TREINO</div><button class="fake-support-btn" disabled>Falar com suporte</button><small>Mensagem fictícia para treinamento.</small>`:`<div class="scare-icon safe">${I('refresh',52)}</div><h2>Atualização de segurança disponível</h2><p>Versão 26.8 • 184 MB • reinicialização necessária.</p><div class="update-row"><span>Pacote de segurança</span><strong>Pronto para instalar</strong></div><small>Nenhum telefone, pagamento ou acesso remoto é solicitado.</small>`}</div></div></div><div class="investigation-layout"><div class="action-panel"><h3>Investigue o alerta sem executar nenhuma instrução.</h3><div class="action-grid"><button class="action-btn" id="inspectOrigin">${I('search')} Examinar a origem da tela</button><button class="action-btn" id="inspectLanguage">${I('file-text')} Analisar o texto do aviso</button><button class="action-btn" id="inspectRequests">${I('list-check')} Identificar o que está sendo pedido</button><button class="action-btn" id="inspectDetails">${I('info')} Ver detalhes técnicos exibidos</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    document.getElementById('inspectOrigin').onclick=origin;document.getElementById('inspectLanguage').onclick=language;document.getElementById('inspectRequests').onclick=requests;document.getElementById('inspectDetails').onclick=details;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'A combinação navegador + urgência + telefone era incompatível com um alerta técnico confiável.':'A origem e o conteúdo eram coerentes com uma atualização normal.',incorrectText:scenario.type==='fraud'?'Observe onde o aviso apareceu e o que ele tenta fazer você executar.':'Nem todo aviso de segurança é golpe; nesta rodada não havia pedido externo ou pressão.'});
  }
  function origin(){record({action:'inspect-origin',label:'Examinou a origem do alerta',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'browser':'system-origin',scenario.type==='fraud'?'Alerta está dentro do navegador':'Aviso veio das configurações locais');window.AntiScamUI.showModal({icon:'search',title:'Origem examinada',html:scenario.type==='fraud'?`O alerta está dentro de uma página aberta no navegador em <strong>${scenario.origin}</strong>.`:'A tela pertence às configurações locais do sistema, não a uma página web.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function language(){record({action:'inspect-language',label:'Analisou a linguagem do alerta',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'pressure':'no-pressure',scenario.type==='fraud'?'Aviso usa ameaça e urgência':'Aviso não usa ameaça para impedir o fechamento');window.AntiScamUI.showModal({icon:'file-text',title:'Linguagem analisada',html:scenario.type==='fraud'?'O texto usa frases como “não feche” e “arquivos em risco” para pressionar uma ação imediata.':'O aviso informa versão, tamanho e necessidade de reiniciar, sem ameaça ou contagem regressiva.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function requests(){record({action:'inspect-requests',label:'Identificou as ações solicitadas pelo alerta',severity:'safe',points:60,trait:'investigator'});if(scenario.type==='fraud'){ev('phone','Mensagem exige ligação para número próprio');ev('remote','Texto menciona acesso remoto');}else{ev('no-phone','Nenhum telefone ou pagamento é solicitado');}window.AntiScamUI.showModal({icon:'list-check',title:'Solicitações identificadas',html:scenario.type==='fraud'?'A página quer que você ligue para um número exibido por ela e menciona que o atendente poderá “assumir o controle” do computador.':'O aviso não pede ligação, pagamento, senha ou instalação de ferramenta externa.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function details(){record({action:'inspect-details',label:'Verificou detalhes técnicos exibidos',severity:'safe',points:60,trait:'investigator'});ev(scenario.type==='fraud'?'browser':'update',scenario.type==='fraud'?'Página não mostra identificação técnica verificável':'Mensagem informa versão e tamanho da atualização');window.AntiScamUI.showModal({icon:'info',title:'Detalhes da tela',html:scenario.type==='fraud'?'Não há versão do sistema, identificador da ameaça ou registro local: apenas texto genérico e um telefone.':'A tela mostra versão 26.8, tamanho do pacote e estado “pronto para instalar”.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function finish(){window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['Pop-ups podem imitar alertas técnicos convincentes.','Observe a origem da tela e o tipo de ação solicitada antes de acreditar na mensagem.','Telefone, acesso remoto e urgência extrema em uma página web são sinais importantes para investigar.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,scenario.type);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Pergunte duas coisas: <strong>onde essa tela realmente está aberta</strong> e <strong>o que ela quer que você faça agora</strong>.',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.SupportSimulation={start,hint};
})();
