(function(){
  const ID='whatsapp'; let root,scenario; const I=(n,s=18)=>window.AntiScamIcons.icon(n,s);
  const scenarios={
    'fraud-lucas':{type:'fraud',name:'Lucas',initials:'L',initial:['Oi! Sou eu, o Lucas. Troquei de número, salva esse aqui.','Tô com um problema e preciso resolver agora.','Você consegue fazer um PIX de R$ 280 pra mim? Amanhã eu te devolvo.'],personalReply:'Nossa, depois te explico isso. Tô numa correria absurda agora. Consegue fazer o PIX primeiro?',callReply:'Agora não dá, meu microfone ficou ruim depois que troquei o aparelho. É rapidinho, só o PIX.',evidence:[{id:'new-number',label:'Contato aparece com número novo'},{id:'urgency',label:'Pedido usa forte urgência'},{id:'money',label:'Há solicitação de PIX'},{id:'evasive',label:'Resposta evita uma pergunta de contexto'},{id:'call-refusal',label:'Contato evita uma confirmação por chamada'}]},
    'fraud-marina':{type:'fraud',name:'Marina',initials:'M',initial:['Oi, é a Marina! Meu chip deu problema e estou usando outro número.','Preciso pagar uma coisa antes que vença. Você consegue me ajudar agora?','É R$ 190 no PIX. Te devolvo mais tarde, prometo.'],personalReply:'Ai, não lembro agora, depois eu vejo isso com calma. Você consegue transferir primeiro?',callReply:'Não consigo atender agora porque estou no meio de um atendimento. Depois te ligo, sério.',evidence:[{id:'new-number',label:'Contato aparece com número novo'},{id:'urgency',label:'Pagamento “precisa” ser imediato'},{id:'money',label:'Há solicitação de transferência'},{id:'evasive',label:'Contato evita responder pergunta pessoal'},{id:'call-refusal',label:'Contato adia confirmação por chamada'}]},
    'legit-lucas':{type:'legit',name:'Lucas',initials:'L',initial:['Oi! Sou o Lucas. Troquei de número hoje.','Não precisa fazer nada agora. Só estou avisando porque o antigo vai ser desativado.','Quando puder, confirma comigo pelo grupo da faculdade antes de salvar este número.'],personalReply:'Claro. A gente entregou o trabalho de redes na terça e você ficou com a parte do diagrama. Se quiser, pergunta mais alguma coisa.',callReply:'Posso sim. Se preferir, também posso responder pelo grupo depois.',evidence:[{id:'new-number',label:'Contato aparece com número novo'},{id:'no-urgency',label:'Não existe pressão para agir'},{id:'no-money',label:'Nenhum dinheiro ou código é pedido'},{id:'coherent',label:'Resposta inclui detalhe coerente de contexto'},{id:'accepts-check',label:'Contato aceita ser verificado'}]}
  };
  const has=a=>window.AntiScamState.getDecisions(ID).some(d=>d.action===a);function record(data){if(has(data.action))return false;window.AntiScamState.recordDecision({challenge:ID,...data});window.AntiScamUI.pointsToast(data.points);return true;}
  const getScenario=()=>scenarios[window.AntiScamState.ensureScenario(ID,Object.keys(scenarios))];const getStep=()=>Number(window.AntiScamState.getChallengeValue(ID,'step',0));const setStep=v=>window.AntiScamState.setChallengeValue(ID,'step',v);const evidenceSlot=()=>`<div id="evidenceSlot">${window.AntiScamUI.evidencePanel(ID,scenario.evidence)}</div>`;function refresh(){const e=document.getElementById('evidenceSlot');if(e)e.innerHTML=window.AntiScamUI.evidencePanel(ID,scenario.evidence);}function ev(id,label){window.AntiScamUI.addEvidence(ID,id,label);refresh();}
  const msg=(text,type='received',time='23:57')=>`<div class="message ${type}">${text}<time>${time}</time></div>`;
  function meta(){return `<div class="sim-meta-bar"><span class="fiction-badge">${I('shield',15)} Simulação educativa • Pessoas e conversa fictícias</span><span>Desafio 3 de 8 • Mensagens</span></div>`;}
  function start(target){root=target;window.AntiScamState.startChallenge(ID);scenario=getScenario();render();}
  function messages(){const step=getStep();const arr=scenario.initial.map((t,i)=>msg(t,'received',`23:${55+i}`));if(step>=1){arr.push(msg('Qual era mesmo a parte do trabalho que a gente fez junto?','sent','23:58'));arr.push(msg(scenario.personalReply,'received','23:58'));}if(step>=2){arr.push(msg('Consegue fazer uma chamada rápida?','sent','23:59'));arr.push(msg(scenario.callReply,'received','23:59'));}return arr.join('');}
  function render(){root.innerHTML=`<div class="sim-frame">${meta()}<div class="chat-scene"><aside class="chat-sidebar"><div class="chat-sidebar-head"><strong>Mensagens</strong><span>${I('message',18)}</span></div><input class="chat-search" value="Pesquisar" readonly><div class="chat-contact"><div class="contact-avatar">${scenario.initials}</div><div><strong>${scenario.name} • novo número</strong><small>${scenario.initial[scenario.initial.length-1]}</small></div></div></aside><section class="chat-main"><div class="chat-head"><div class="contact-avatar">${scenario.initials}</div><div><strong>${scenario.name}</strong><small>número não salvo • online</small></div><span class="chat-head-actions">${I('video',18)} ${I('phone',18)}</span></div><div class="chat-area" id="chatArea">${messages()}</div><div><div class="training-chat-note">Treinamento: não há envio de mensagens, chamadas ou transferências reais.</div><div class="chat-compose"><input placeholder="Digite uma mensagem..." readonly><button disabled>${I('send',18)}</button></div></div></section></div><div class="investigation-layout"><div class="action-panel"><h3>Procure sinais na conversa antes de concluir.</h3><div class="action-grid"><button class="action-btn" id="inspectContext">${I('search')} Analisar o contexto</button><button class="action-btn" id="inspectProfile">${I('user')} Examinar o perfil e o número</button><button class="action-btn" id="askPersonal">${I('message')} Fazer uma pergunta de contexto</button><button class="action-btn" id="askCall">${I('video')} Pedir uma chamada</button></div>${window.AntiScamUI.classificationPanel(ID)}</div>${evidenceSlot()}</div></div>`;
    setTimeout(()=>{const a=document.getElementById('chatArea');if(a)a.scrollTop=a.scrollHeight;},10);document.getElementById('inspectContext').onclick=context;document.getElementById('inspectProfile').onclick=profile;document.getElementById('askPersonal').onclick=personal;document.getElementById('askCall').onclick=call;
    window.AntiScamUI.bindClassification({challenge:ID,actualType:scenario.type,onFinish:finish,correctText:scenario.type==='fraud'?'Novo número, urgência, dinheiro e resistência à verificação formavam um padrão forte.':'O contato novo não pressionava, não pedia dinheiro e aceitava verificação.',incorrectText:scenario.type==='fraud'?'Releia como o contato reage quando você tenta verificar algo.':'Número novo sozinho não basta para concluir fraude.'});
  }
  function context(){record({action:'inspect-context',label:'Analisou o contexto da conversa',severity:'safe',points:55,trait:'investigator'});ev('new-number','Contato aparece com número novo');if(scenario.type==='fraud'){ev('urgency','Urgência identificada');ev('money','Pedido financeiro identificado');}else{ev('no-urgency','Ausência de pressão identificada');ev('no-money','Nenhum pedido financeiro identificado');}window.AntiScamUI.showModal({icon:'search',title:'Contexto analisado',html:scenario.type==='fraud'?'Número novo, urgência e pedido de dinheiro aparecem juntos. A combinação é mais importante do que qualquer item isolado.':'Há um número novo, mas não existe pedido de dinheiro, código ou ação urgente.',actions:[{label:'Continuar',className:'btn-primary'}]});}
  function profile(){record({action:'inspect-profile',label:'Examinou perfil e número',severity:'safe',points:55,trait:'investigator'});ev('new-number','Número não está salvo e é diferente do contato anterior');window.AntiScamUI.showModal({icon:'user',title:'Perfil examinado',html:`O número não está salvo e a foto é apenas a inicial “${scenario.initials}”. A descrição diz “novo número”. Isso <strong>não prova</strong> fraude por si só.`,actions:[{label:'Continuar',className:'btn-primary'}]});}
  function personal(){record({action:'personal-question',label:'Fez uma pergunta de contexto',severity:'safe',points:65,trait:'investigator'});setStep(Math.max(getStep(),1));if(scenario.type==='fraud')ev('evasive','Contato evitou responder a pergunta');else ev('coherent','Resposta inclui detalhe coerente de contexto');window.AntiScamUI.feedback('info',scenario.type==='fraud'?'A resposta desviou da pergunta':'A resposta trouxe contexto',scenario.type==='fraud'?'O contato não respondeu o detalhe e tentou voltar ao pedido financeiro.':'A resposta cita um detalhe específico da relação simulada e não cria pressão para agir.',render);}
  function call(){record({action:'ask-call',label:'Pediu uma chamada para observar a reação',severity:'safe',points:65,trait:'investigator'});setStep(Math.max(getStep(),2));if(scenario.type==='fraud')ev('call-refusal','Contato evita uma confirmação por chamada');else ev('accepts-check','Contato aceita ser verificado');window.AntiScamUI.feedback('info',scenario.type==='fraud'?'O contato evita a chamada':'O contato aceita a verificação',scenario.type==='fraud'?'A desculpa pode existir na vida real, mas somada aos outros sinais aumenta a suspeita.':'A pessoa aceita chamada ou outra forma de confirmação e não condiciona isso a nenhuma transferência.',render);}
  function finish(){if(window.AntiScamState.getEvidence(ID).length>=4)window.AntiScamUI.achievement('leitor-de-contexto','Leitor de Contexto');window.AntiScamState.completeChallenge(ID);window.AntiScamApp.showChallengeResult(ID,['Número novo é apenas um sinal inicial, não uma prova automática de fraude.','Urgência, pedido de dinheiro e resistência à verificação ganham força quando aparecem juntos.','Faça perguntas de contexto e observe como a pessoa reage a tentativas simples de confirmação.']);}
  function hint(){const used=window.AntiScamState.useHint(ID,`${scenario.type}-${getStep()}`);window.AntiScamUI.updateHeader();window.AntiScamUI.showModal({icon:'lightbulb',title:used?'Pista (-35 pontos)':'Pista já utilizada',html:'Observe menos o que a pessoa <em>diz que é</em> e mais <strong>o padrão da conversa: urgência, dinheiro, contexto e reação à verificação</strong>.',actions:[{label:'Voltar',className:'btn-primary'}]});}
  window.WhatsAppSimulation={start,hint};
})();
